import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/next_theme";
import { ReactQueryProvider } from "@/providers/query_client_provider";
import { Toaster } from "@/components/ui/sonner";

import ReduxProvider from "@/providers/redux-provider";
import AuthCheck from "@/providers/auth_provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <AuthCheck>
              <ReactQueryProvider> {children}</ReactQueryProvider>
            </AuthCheck>
          </ReduxProvider>
        </ThemeProvider>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
